apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "expense-tracker.fullname" . }}
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "expense-tracker.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "expense-tracker.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "expense-tracker.serviceAccountName" . }}

      containers:
        - name: expense-tracker

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.container.port }}

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "expense-tracker.fullname" . }}-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "expense-tracker.fullname" . }}-config
                  key: SPRING_DATASOURCE_USERNAME

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "expense-tracker.fullname" . }}-config
                  key: SERVER_PORT

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "expense-tracker.fullname" . }}-secret
                  key: SPRING_DATASOURCE_PASSWORD

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}

      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}

      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}