apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expense-tracker.fullname" . }}-secret
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}
type: Opaque

stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.SPRING_DATASOURCE_PASSWORD | quote }}