version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - appbridge
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

  mainapp:
  environment:
    DB_URL: jdbc:mysql://mysql:3306/expenses_tracker?useSSL=false&serverTimezone=UTC
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    SERVER_PORT: 8080  # Internal port
  ports:
    - "8081:8080"
    networks:
      - appbridge
    depends_on:
      - mysql
    restart: always

networks:
  appbridge:
    #external: true

volumes:
  mysql-data:
